version: '3.1'

services:
    nginx:
        image: nginx
        labels:
            - traefik.http.routers.nginx.rule=Host(`nginx.localhost`)
        #     - traefik.http.services.my-service.loadbalancer.server.port=12345
    apache:
        image: httpd
        labels:
            - traefik.http.routers.apache.rule=Host(`apache.localhost`)
        #     - traefik.http.services.my-service.loadbalancer.server.port=12345
    traefik:
        image: traefik
        ports: 
            # dashboard
            - "8080:8080"
            # serve requests
            - "80:80"
        volumes:
            - ./traefik.yml:/etc/traefik/traefik.yml
            - ./file_provider:/etc/traefik/file_provider
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on: 
            - nginx
            - apache
