# Docker configuration backend
providers:
    providersThrottleDuration: 1s
    docker:
        defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

    file:
        directory: /etc/traefik/file_provider
        watch: true
  
# API and dashboard configuration
api:
    insecure: true